<a href="https://colab.research.google.com/github/venu887/Python-Codes/blob/main/Basics%20of%20python/Copy_of_Python_preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print ("hello venu")
print (" my age is 31")
print ("i am finished my Doctorial degree now")
print ("i am looking for job or Postdoc now to fit")

hello venu
 my age is 31
i am finished my Doctorial degree now
i am looking for job or Postdoc now to fit


In [ ]:
print("\      /")
print(" \    / ")
print("  \  /  ")
print("   \/   ")

\      /
 \    / 
  \  /  
   \/   


In [ ]:
print("There once was a man named venu")
print("he was 30 years old")
print("he reallky liked the name venugopala")
print("but he didn't like being 30")

There once was a man named venu
he was 30 years old
he reallky liked the name venugopala
but he didn't like being 30


In [ ]:
character_name= "venu"
character_age = "30"
print("There once was a man named "+ character_name +", ")
print("he was "+charecter_age+ " years old")
print("he reallky liked the name " + character_name + "gopala")
print("but he didn't like being "+ charecter_age+".")

There once was a man named venu, 
he was 30 years old
he reallky liked the name venugopala
but he didn't like being 30.


In [ ]:
character_name= "venu"
character_age = 30 
# age= "30"
is_male=True
print("There once was a man named "+ character_name +", ")
print("he was "+charecter_age+ " years old")
character_name="mekala venugopala reddy"

print("he reallky liked the name " + character_name + " ")
print("but he didn't like being "+ charecter_age+".")

There once was a man named venu, 
he was 30 years old
he reallky liked the name mekala venugopala reddy 
but he didn't like being 30.


In [ ]:
# Working with strings: plain text
print("venugopal academy")
print("venugopala\nacademy")
print("venugopala\"academy")
print("venugopala\academy")
phrase = "venugopala academy"
print(phrase+ " is cool")
# function to modify our strings
print(phrase.upper())
print(phrase.upper().isupper())
print(len(phrase))
print(phrase[0])
print(phrase[2])
# index function
print(phrase.index("nu"))
print(phrase.replace("venu","gopal"))

venugopal academy
venugopala
academy
venugopala"academy
venugopalacademy
venugopala academy is cool
VENUGOPALA ACADEMY
True
18
v
n
2
gopalgopala academy


In [ ]:
# working with numbers
print(2)
print(2.987)
print(-878993)
print(4+5)
print(4*5+6)
print(4*(5+8))
print(5%3)
x=5
print(x)
print(str(x)+" my favourite number")
my_num=-5
print(abs(my_num)) #absolute value
print(pow(3,2)) # 3 to the power of 2
print(max(4,5,6))
print(min(5,6,3,6,7))
print(round(8.7))
# import  function for maths
from math import*
print(floor(5.6))
print(ceil(5.7))
print(sqrt(36))

2
2.987
-878993
9
26
52
2
5
5 my favourite number
5
9.0
6
3
9
5
6
6.0


In [ ]:
# getting input from users
name=input("Enter your name: ")
age=input("Enter your age: ")
print("Hello " + name + "! You are "+ age)


Enter your name: venu
Enter your age: 30
Hello venu! You are 30


In [ ]:
#building a basic calculator
num1=input("Enter a number: ")
num2=input("Enter another number: ")
result=num1+num2
print(result)
results=int(num1) + int(num2) #a whole number INT 
print(results)
results1=float(num1) + float(num2) # float for decimels
print(results1)

Enter a number: 2
Enter another number: 3
23
5


In [ ]:
# mad libs game
print("Roses are red")
print("Violets are blue")
print("I love you")

color= input("Enter a color: ")
plural_noun= input("Enter a Plural Noun: ")
celebraty= input("Enter a celebraty: ")
print("Roses are "+ color)
print(plural_noun + " are blue")
print("I love " + celebraty)

Roses are red
Violets are blue
I love you
Enter a color: red
Enter a Plural Noun: violine
Enter a celebraty: venu
Roses are red
violine are blue
I love venu


In [ ]:
# working with lists in python
friends = ["venu", "gopal", "reddy"]
print(friends)
print(friends[0])
print(friends[2])
print(friends[1:])
print(friends[1:3]) #Select specific elements
#modify value
friends[1]="Mekala"
print(friends[1])


['venu', 'gopal', 'reddy']
venu
reddy
['gopal', 'reddy']
['gopal', 'reddy']
Mekala


In [ ]:
# List Functions
lucky_numbers= [4,5,6,3,2,44,34]
friends=["venu","mekala", "gopala","reddy", "sri", "supreeth"]
friends.extend(lucky_numbers) # insert both lists
friends.append("lakshman") # add iteam end of list
friends.insert(1,"aruna") # add something at position one
friends.remove("venu") # remove one element 
friends.clear() # remove all list
friends.pop() #removes last element in list
print(friends)
print(friends.index("venu")) 
print(friends.count("venu")) # How many times this nam occurs
friends.sort() # it put everything in alphabetical order
lucky_numbers.reverse() # make the numbers into riverse

friends2=friends.copy() # coping a list

['aruna', 'mekala', 'gopala', 'reddy', 'sri', 'supreeth', 4, 5, 6, 3, 2, 44, 34, 'lakshman']


In [ ]:
#Tuples in python it will store multiple values
coordinates = [(4,5),(6,7), (8,7)]
print(coordinates[0])
print(coordinates[1])
coordinates[1] = 10 

(4, 5)
10


In [ ]:
#Functions collection of code to perform specific task
def sayhitovenu():
  print("Hello venu")

print("Top")
sayhitovenu()
print("Bottom")

Top
Hello venu
Bottom


In [ ]:
def sayhi(name):
  print("Hello "+ name)

sayhi("Venu")
sayhi("Uma")

Hello Venu
Hello Uma


In [ ]:
def sayhi(name, age):
  print("Hello "+ name+ " you are "+ age)

sayhi("Venu", "31")
sayhi("Uma", "24")

Hello Venu you are 31
Hello Uma you are 24


In [ ]:
def sayhi(name, age):
  print("Hello "+ name+ " you are "+ str(age))

sayhi("Venu", 31)
sayhi("Uma", 24)

Hello Venu you are 31
Hello Uma you are 24


In [2]:
# https://www.oreilly.com/library/view/elegant-scipy/9781491922927/ch01.html
# TCGA DEG analysis in pythin
# key SciPy concepts along the way to DEG analysis
import numpy as np
import pandas as pd
def rpkm(counts, lengths):
    """Calculate reads per kilobase transcript per million reads.

    RPKM = (10^9 * C) / (N * L)

    Where:
    C = Number of reads mapped to a gene
    N = Total mapped reads in the experiment
    L = Exon length in base pairs for a gene

    Parameters
    ----------
    counts: array, shape (N_genes, N_samples)
        RNAseq (or similar) count data where columns are individual samples
        and rows are genes.
    lengths: array, shape (N_genes,)
        Gene lengths in base pairs in the same order
        as the rows in counts.

    Returns
    -------
    normed : array, shape (N_genes, N_samples)
        The RPKM normalized counts matrix.
    """
    N = np.sum(counts, axis=0)  # sum each column to get total reads per sample
    L = lengths
    C = counts

    normed = 1e9 * C / (N[np.newaxis, :] * L[:, np.newaxis])

    return(normed)

In [ ]:
# Example
gene0 = [100, 200]
gene1 = [50, 0]
gene2 = [350, 100]
expression_data = [gene0, gene1, gene2]
print(expression_data)

[[100, 200], [50, 0], [350, 100]]


In [ ]:
expression_data[2][0]

350

In [ ]:
array1d=np.array([1,2,3,4])
print(array1d)
print(type(array1d))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
print(array1d.shape)

(4,)


In [ ]:
array2d=np.array(expression_data)
print(array2d)
print(array2d.shape)
print(type(array2d))

[[100 200]
 [ 50   0]
 [350 100]]
(3, 2)
<class 'numpy.ndarray'>


In [ ]:
print(array2d.ndim)

2


In [ ]:
# create an ndarray of integers in the range
# 0 up to (but not including) 1000000
array=np.arange(1e6)
# convert it to a list
list_array=array.tolist()

In [ ]:
%timeit -n10 y=[val*5 for val in list_array]

106 ms ± 4.59 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
%timeit -n10 x = array * 5

2.25 ms ± 412 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [3]:
# create an ndarray y
y= np.array ([1,2,3,4], np.int32)
print(y)

[1 2 3 4]


In [6]:
# Create a sub in y
x = y[:2]
print(x)

[1 2]


In [8]:
# change first element in x from 1 to 8
x[0] =8
print(x)

[8 2]


In [9]:
# Here we can obsaerved that x is a sub part of y- array so if x changes y also changes the element
print(y)

[8 2 3 4]


In [10]:
# Vectarization 
y = np.array([1,2,3,4,5,6])
print(y)

[1 2 3 4 5 6]


In [11]:
# we can multiplay whole array with single number can apply for every element in array
print(y*8)

[ 8 16 24 32 40 48]


In [15]:
x = np.array([0,7,9,6,5,3])
print(x)

[0 7 9 6 5 3]


In [16]:
# both x and y must have same lenght.
print(y+x)

[ 1  9 12 10 10  9]


In [20]:
# Broadcasting 
x= np.array([1,2,3,4,9])
x=np.reshape(x, (len(x),1))
print(x)

[[1]
 [2]
 [3]
 [4]
 [9]]


In [18]:
y=np.array([0,7,8,9,6])
y=np.reshape(y,(1,len(y)))
print(y)

[[0 7 8 9 6]]


In [21]:
print(x.shape)
print(y.shape)

(5, 1)
(1, 5)


In [22]:
outer=x*y
print(outer)

[[ 0  7  8  9  6]
 [ 0 14 16 18 12]
 [ 0 21 24 27 18]
 [ 0 28 32 36 24]
 [ 0 63 72 81 54]]


In [23]:
print(outer.shape)

(5, 5)


In [24]:
# Exploring a Gene Expression Dataset
# Reading the data with pandas
import pandas as pd
import numpy as np

In [27]:
# Import TCGA melanoma data
filename= 'data/counts.txt'
with open(filename, 'rt') as D:
  data_table =pd.read_csv(D, index_col=0)

  print(data_table.iloc[:5,:5])

FileNotFoundError: ignored

In [ ]:
# Sample names
samples = list(data_table.columns)

In [ ]:
# Import gene lengths
filename = 'data/genes.csv'
with open(filename, 'rt') as f:
    # Parse file with pandas, index by GeneSymbol
    gene_info = pd.read_csv(f, index_col=0)
print(gene_info.iloc[:5, :])

In [ ]:
print("Genes in data_table: ", data_table.shape[0])
print("Genes in gene_info: ", gene_info.shape[0])

In [ ]:
# Subset gene info to match the count data
matched_index = pd.Index.intersection(data_table.index, gene_info.index)

In [ ]:
# 2D ndarray containing expression counts for each gene in each individual
counts = np.asarray(data_table.loc[matched_index], dtype=int)

gene_names = np.array(matched_index)

# Check how many genes and individuals were measured
print(f'{counts.shape[0]} genes measured in {counts.shape[1]} individuals.')

In [ ]:
# 1D ndarray containing the lengths of each gene
gene_lengths = np.asarray(gene_info.loc[matched_index]['GeneLength'],
                          dtype=int)

In [ ]:
print(counts.shape)
print(gene_lengths.shape)

In [ ]:
# Normalization
# Make all plots appear inline in the Jupyter notebook from now onwards
%matplotlib inline
# Use our own style file for the plots
import matplotlib.pyplot as plt
plt.style.use('style/elegant.mplstyle')

In [ ]:
total_counts = np.sum(counts, axis=0)  # sum columns together
                                       # (axis=1 would sum rows)

from scipy import stats

# Use Gaussian smoothing to estimate the density
density = stats.kde.gaussian_kde(total_counts)

# Make values for which to estimate the density, for plotting
x = np.arange(min(total_counts), max(total_counts), 10000)

# Make the density plot
fig, ax = plt.subplots()
ax.plot(x, density(x))
ax.set_xlabel("Total counts per individual")
ax.set_ylabel("Density")

plt.show()

print(f'Count statistics:\n  min:  {np.min(total_counts)}'
      f'\n  mean: {np.mean(total_counts)}'
      f'\n  max:  {np.max(total_counts)}')

In [ ]:
# Subset data for plotting
np.random.seed(seed=7) # Set seed so we will get consistent results
# Randomly select 70 samples
samples_index = np.random.choice(range(counts.shape[1]), size=70, replace=False)
counts_subset = counts[:, samples_index]

In [ ]:
# Some custom x-axis labelling to make our plots easier to read
def reduce_xaxis_labels(ax, factor):
    """Show only every ith label to prevent crowding on x-axis
        e.g. factor = 2 would plot every second x-axis label,
        starting at the first.

    Parameters
    ----------
    ax : matplotlib plot axis to be adjusted
    factor : int, factor to reduce the number of x-axis labels by
    """
    plt.setp(ax.xaxis.get_ticklabels(), visible=False)
    for label in ax.xaxis.get_ticklabels()[factor-1::factor]:
        label.set_visible(True)

In [ ]:
# Bar plot of expression counts by individual
fig, ax = plt.subplots(figsize=(4.8, 2.4))

with plt.style.context('style/thinner.mplstyle'):
    ax.boxplot(counts_subset)
    ax.set_xlabel("Individuals")
    ax.set_ylabel("Gene expression counts")
    reduce_xaxis_labels(ax, 5)

In [ ]:
# Bar plot of expression counts by individual
fig, ax = plt.subplots(figsize=(4.8, 2.4))

with plt.style.context('style/thinner.mplstyle'):
    ax.boxplot(np.log(counts_subset + 1))
    ax.set_xlabel("Individuals")
    ax.set_ylabel("log gene expression counts")
    reduce_xaxis_labels(ax, 5)

In [ ]:
# Normalize by library size
# Divide the expression counts by the total counts for that individual
# Multiply by 1 million to get things back in a similar scale
counts_lib_norm = counts / total_counts * 1000000
# Notice how we just used broadcasting twice there!
counts_subset_lib_norm = counts_lib_norm[:,samples_index]

# Bar plot of expression counts by individual
fig, ax = plt.subplots(figsize=(4.8, 2.4))

with plt.style.context('style/thinner.mplstyle'):
    ax.boxplot(np.log(counts_subset_lib_norm + 1))
    ax.set_xlabel("Individuals")
    ax.set_ylabel("log gene expression counts")
    reduce_xaxis_labels(ax, 5)

In [ ]:
import itertools as it
from collections import defaultdict


def class_boxplot(data, classes, colors=None, **kwargs):
    """Make a boxplot with boxes colored according to the class they belong to.

    Parameters
    ----------
    data : list of array-like of float
        The input data. One boxplot will be generated for each element
        in `data`.
    classes : list of string, same length as `data`
        The class each distribution in `data` belongs to.

    Other parameters
    ----------------
    kwargs : dict
        Keyword arguments to pass on to `plt.boxplot`.
    """
    all_classes = sorted(set(classes))
    colors = plt.rcParams['axes.prop_cycle'].by_key()['color']
    class2color = dict(zip(all_classes, it.cycle(colors)))

    # map classes to data vectors
    # other classes get an empty list at that position for offset
    class2data = defaultdict(list)
    for distrib, cls in zip(data, classes):
        for c in all_classes:
            class2data[c].append([])
        class2data[cls][-1] = distrib

    # then, do each boxplot in turn with the appropriate color
    fig, ax = plt.subplots()
    lines = []
    for cls in all_classes:
        # set color for all elements of the boxplot
        for key in ['boxprops', 'whiskerprops', 'flierprops']:
            kwargs.setdefault(key, {}).update(color=class2color[cls])
        # draw the boxplot
        box = ax.boxplot(class2data[cls], **kwargs)
        lines.append(box['whiskers'][0])
    ax.legend(lines, all_classes)
    return ax

In [ ]:
log_counts_3 = list(np.log(counts.T[:3] + 1))
log_ncounts_3 = list(np.log(counts_lib_norm.T[:3] + 1))
ax = class_boxplot(log_counts_3 + log_ncounts_3,
                   ['raw counts'] * 3 + ['normalized by library size'] * 3,
                   labels=[1, 2, 3, 1, 2, 3])
ax.set_xlabel('sample number')
ax.set_ylabel('log gene expression counts');


In [ ]:
def binned_boxplot(x, y, *,  # check out this Python 3 exclusive! (*see tip box)
                   xlabel='gene length (log scale)',
                   ylabel='average log counts'):
    """Plot the distribution of `y` dependent on `x` using many boxplots.

    Note: all inputs are expected to be log-scaled.

    Parameters
    ----------
    x: 1D array of float
        Independent variable values.
    y: 1D array of float
        Dependent variable values.
    """
    # Define bins of `x` depending on density of observations
    x_hist, x_bins = np.histogram(x, bins='auto')

    # Use `np.digitize` to number the bins
    # Discard the last bin edge because it breaks the right-open assumption
    # of `digitize`. The max observation correctly goes into the last bin.
    x_bin_idxs = np.digitize(x, x_bins[:-1])

    # Use those indices to create a list of arrays, each containing the `y`
    # values corresponding to `x`s in that bin. This is the input format
    # expected by `plt.boxplot`
    binned_y = [y[x_bin_idxs == i]
                for i in range(np.max(x_bin_idxs))]
    fig, ax = plt.subplots(figsize=(4.8,1))

    # Make the x-axis labels using the bin centers
    x_bin_centers = (x_bins[1:] + x_bins[:-1]) / 2
    x_ticklabels = np.round(np.exp(x_bin_centers)).astype(int)

    # make the boxplot
    ax.boxplot(binned_y, labels=x_ticklabels)

    # show only every 10th label to prevent crowding on x-axis
    reduce_xaxis_labels(ax, 10)

    # Adjust the axis names
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel);

In [ ]:
>>> binned_boxplot(x, y, xlabel='my x label', ylabel='my y label')

In [ ]:
>>> binned_boxplot(x, y, 'my x label', 'my y label')

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-58-7a118d2d5750in <module>()
    1 x_vals = [1, 2, 3, 4, 5]
    2 y_vals = [1, 2, 3, 4, 5]
----3 binned_boxplot(x, y, 'my x label', 'my y label')

TypeError: binned_boxplot() takes 2 positional arguments but 4 were given

In [ ]:
binned_boxplot(x, y, 'my y label')

In [ ]:
log_counts = np.log(counts_lib_norm + 1)
mean_log_counts = np.mean(log_counts, axis=1)  # across samples
log_gene_lengths = np.log(gene_lengths)

with plt.style.context('style/thinner.mplstyle'):
    binned_boxplot(x=log_gene_lengths, y=mean_log_counts)

In [ ]:
#Normalizing Over Samples and Genes: RPKM
# Make our variable names the same as the RPKM formula so we can compare easily
C = counts
N = counts.sum(axis=0)  # sum each column to get total reads per sample
L = gene_lengths  # lengths for each gene, matching rows in `C`

In [ ]:
# Multiply all counts by 10^9
C_tmp = 10^9 * C

In [ ]:
print('C_tmp.shape', C_tmp.shape)
print('L.shape', L.shape)
C_tmp.shape (20500, 375)
L.shape (20500,)

In [ ]:
L = L[:, np.newaxis] # append a dimension to L, with value 1
print('C_tmp.shape', C_tmp.shape)
print('L.shape', L.shape)

In [ ]:
# Divide each row by the gene length for that gene (L)
C_tmp = C_tmp / L

In [ ]:
# Check the shapes of C_tmp and N
print('C_tmp.shape', C_tmp.shape)
print('N.shape', N.shape)

In [ ]:
# Divide each column by the total counts for that column (N)
N = N[np.newaxis, :]
print('C_tmp.shape', C_tmp.shape)
print('N.shape', N.shape)

In [ ]:
# Divide each column by the total counts for that column (N)
rpkm_counts = C_tmp / N

In [ ]:
def rpkm(counts, lengths):
    """Calculate reads per kilobase transcript per million reads.

    RPKM = (10^9 * C) / (N * L)

    Where:
    C = Number of reads mapped to a gene
    N = Total mapped reads in the experiment
    L = Exon length in base pairs for a gene

    Parameters
    ----------
    counts: array, shape (N_genes, N_samples)
        RNAseq (or similar) count data where columns are individual samples
        and rows are genes.
    lengths: array, shape (N_genes,)
        Gene lengths in base pairs in the same order
        as the rows in counts.

    Returns
    -------
    normed : array, shape (N_genes, N_samples)
        The RPKM normalized counts matrix.
    """
    N = np.sum(counts, axis=0)  # sum each column to get total reads per sample
    L = lengths
    C = counts

    normed = 1e9 * C / (N[np.newaxis, :] * L[:, np.newaxis])

    return(normed)

In [ ]:
counts_rpkm = rpkm(counts, gene_lengths)

In [ ]:
# RPKM between gene normalization
log_counts = np.log(counts + 1)
mean_log_counts = np.mean(log_counts, axis=1)
log_gene_lengths = np.log(gene_lengths)

with plt.style.context('style/thinner.mplstyle'):
    binned_boxplot(x=log_gene_lengths, y=mean_log_counts)

In [ ]:
log_counts = np.log(counts_rpkm + 1)
mean_log_counts = np.mean(log_counts, axis=1)
log_gene_lengths = np.log(gene_lengths)

with plt.style.context('style/thinner.mplstyle'):
    binned_boxplot(x=log_gene_lengths, y=mean_log_counts)

In [ ]:
gene_idxs = np.array([80, 186])
gene1, gene2 = gene_names[gene_idxs]
len1, len2 = gene_lengths[gene_idxs]
gene_labels = [f'{gene1}, {len1}bp', f'{gene2}, {len2}bp']

log_counts = list(np.log(counts[gene_idxs] + 1))
log_ncounts = list(np.log(counts_rpkm[gene_idxs] + 1))

ax = class_boxplot(log_counts,
                   ['raw counts'] * 3,
                   labels=gene_labels)
ax.set_xlabel('Genes')
ax.set_ylabel('log gene expression counts over all samples');

In [ ]:
ax = class_boxplot(log_ncounts,
                   ['RPKM normalized'] * 3,
                   labels=gene_labels)
ax.set_xlabel('Genes')
ax.set_ylabel('log RPKM gene expression counts over all samples');

In [ ]:
# Chapter 2. Quantile Normalization with NumPy and SciPy
import numpy as np
from scipy import stats

def quantile_norm(X):
    """Normalize the columns of X to each have the same distribution.

    Given an expression matrix (microarray data, read counts, etc) of M genes
    by N samples, quantile normalization ensures all samples have the same
    spread of data (by construction).

    The data across each row are averaged to obtain an average column. Each
    column quantile is replaced with the corresponding quantile of the average
    column.

    Parameters
    ----------
    X : 2D array of float, shape (M, N)
        The input data, with M rows (genes/features) and N columns (samples).

    Returns
    -------
    Xn : 2D array of float, shape (M, N)
        The normalized data.
    """
    # compute the quantiles
    quantiles = np.mean(np.sort(X, axis=0), axis=1)

    # compute the column-wise ranks. Each observation is replaced with its
    # rank in that column: the smallest observation is replaced by 1, the
    # second-smallest by 2, ..., and the largest by M, the number of rows.
    ranks = np.apply_along_axis(stats.rankdata, 0, X)

    # convert ranks to integer indices from 0 to M-1
    rank_indices = ranks.astype(int) - 1

    # index the quantiles for each rank with the ranks matrix
    Xn = quantiles[rank_indices]

    return(Xn)

In [ ]:
def quantile_norm_log(X):
    logX = np.log(X + 1)
    logXn = quantile_norm(logX)
    return logXn

In [ ]:
import numpy as np
import pandas as pd

# Import TCGA melanoma data
filename = 'data/counts.txt'
data_table = pd.read_csv(filename, index_col=0)  # Parse file with pandas

print(data_table.iloc[:5, :5])

In [ ]:
#Gene Expression Distribution Differences Between Individuals
# Make plots appear inline, set custom plotting style
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('style/elegant.mplstyle')

In [ ]:
from scipy import stats

def plot_col_density(data):
    """For each column, produce a density plot over all rows."""

    # Use Gaussian smoothing to estimate the density
    density_per_col = [stats.gaussian_kde(col) for col in data.T]
    x = np.linspace(np.min(data), np.max(data), 100)

    fig, ax = plt.subplots()
    for density in density_per_col:
        ax.plot(x, density(x))
    ax.set_xlabel('Data values (per column)')
    ax.set_ylabel('Density')

In [ ]:
# Before normalization
log_counts = np.log(counts + 1)
plot_col_density(log_counts)

In [ ]:
import numpy as np
from scipy import stats

def quantile_norm(X):
    """Normalize the columns of X to each have the same distribution.

    Given an expression matrix (microarray data, read counts, etc.) of M genes
    by N samples, quantile normalization ensures all samples have the same
    spread of data (by construction).

    The data across each row are averaged to obtain an average column. Each
    column quantile is replaced with the corresponding quantile of the average
    column.

    Parameters
    ----------
    X : 2D array of float, shape (M, N)
        The input data, with M rows (genes/features) and N columns (samples).

    Returns
    -------
    Xn : 2D array of float, shape (M, N)
        The normalized data.
    """
    # compute the quantiles
    quantiles = np.mean(np.sort(X, axis=0), axis=1)

    # compute the column-wise ranks. Each observation is replaced with its
    # rank in that column: the smallest observation is replaced by 1, the
    # second-smallest by 2, ..., and the largest by M, the number of rows.
    ranks = np.apply_along_axis(stats.rankdata, 0, X)

    # convert ranks to integer indices from 0 to M-1
    rank_indices = ranks.astype(int) - 1

    # index the quantiles for each rank with the ranks matrix
    Xn = quantiles[rank_indices]

    return(Xn)


def quantile_norm_log(X):
    logX = np.log(X + 1)
    logXn = quantile_norm(logX)
    return logXn

In [ ]:
# After normalization
log_counts_normalized = quantile_norm_log(counts)

plot_col_density(log_counts_normalized)

In [ ]:
#Biclustering the Counts Data
def most_variable_rows(data, *, n=1500):
    """Subset data to the n most variable rows

    In this case, we want the n most variable genes.

    Parameters
    ----------
    data : 2D array of float
        The data to be subset
    n : int, optional
        Number of rows to return.

    Returns
    -------
    variable_data : 2D array of float
        The `n` rows of `data` that exhibit the most variance.
    """
    # compute variance along the columns axis
    rowvar = np.var(data, axis=1)
    # Get sorted indices (ascending order), take the last n
    sort_indices = np.argsort(rowvar)[-n:]
    # use as index for data
    variable_data = data[sort_indices, :]
    return variable_data

In [ ]:
from scipy.cluster.hierarchy import linkage


def bicluster(data, linkage_method='average', distance_metric='correlation'):
    """Cluster the rows and the columns of a matrix.

    Parameters
    ----------
    data : 2D ndarray
        The input data to bicluster.
    linkage_method : string, optional
        Method to be passed to `linkage`.
    distance_metric : string, optional
        Distance metric to use for clustering. See the documentation
        for ``scipy.spatial.distance.pdist`` for valid metrics.

    Returns
    -------
    y_rows : linkage matrix
        The clustering of the rows of the input data.
    y_cols : linkage matrix
        The clustering of the cols of the input data.
    """
    y_rows = linkage(data, method=linkage_method, metric=distance_metric)
    y_cols = linkage(data.T, method=linkage_method, metric=distance_metric)
    return y_rows, y_cols

In [ ]:
# Visualizing Clusters
from scipy.cluster.hierarchy import dendrogram, leaves_list


def clear_spines(axes):
    for loc in ['left', 'right', 'top', 'bottom']:
        axes.spines[loc].set_visible(False)
    axes.set_xticks([])
    axes.set_yticks([])


def plot_bicluster(data, row_linkage, col_linkage,
                   row_nclusters=10, col_nclusters=3):
    """Perform a biclustering, plot a heatmap with dendrograms on each axis.

    Parameters
    ----------
    data : array of float, shape (M, N)
        The input data to bicluster.
    row_linkage : array, shape (M-1, 4)
        The linkage matrix for the rows of `data`.
    col_linkage : array, shape (N-1, 4)
        The linkage matrix for the columns of `data`.
    n_clusters_r, n_clusters_c : int, optional
        Number of clusters for rows and columns.
    """
    fig = plt.figure(figsize=(4.8, 4.8))

    # Compute and plot row-wise dendrogram
    # `add_axes` takes a "rectangle" input to add a subplot to a figure.
    # The figure is considered to have side-length 1 on each side, and its
    # bottom-left corner is at (0, 0).
    # The measurements passed to `add_axes` are the left, bottom, width, and
    # height of the subplot. Thus, to draw the left dendrogram (for the rows),
    # we create a rectangle whose bottom-left corner is at (0.09, 0.1), and
    # measuring 0.2 in width and 0.6 in height.
    ax1 = fig.add_axes([0.09, 0.1, 0.2, 0.6])
    # For a given number of clusters, we can obtain a cut of the linkage
    # tree by looking at the corresponding distance annotation in the linkage
    # matrix.
    threshold_r = (row_linkage[-row_nclusters, 2] +
                   row_linkage[-row_nclusters+1, 2]) / 2
    with plt.rc_context({'lines.linewidth': 0.75}):
        dendrogram(row_linkage, orientation='left',
                   color_threshold=threshold_r, ax=ax1)
    clear_spines(ax1)

    # Compute and plot column-wise dendrogram
    # See notes above for explanation of parameters to `add_axes`
    ax2 = fig.add_axes([0.3, 0.71, 0.6, 0.2])
    threshold_c = (col_linkage[-col_nclusters, 2] +
                   col_linkage[-col_nclusters+1, 2]) / 2
    with plt.rc_context({'lines.linewidth': 0.75}):
        dendrogram(col_linkage, color_threshold=threshold_c, ax=ax2)
    clear_spines(ax2)

    # Plot data heatmap
    ax = fig.add_axes([0.3, 0.1, 0.6, 0.6])

    # Sort data by the dendrogram leaves
    idx_rows = leaves_list(row_linkage)
    data = data[idx_rows, :]
    idx_cols = leaves_list(col_linkage)
    data = data[:, idx_cols]

    im = ax.imshow(data, aspect='auto', origin='lower', cmap='YlGnBu_r')
    clear_spines(ax)

    # Axis labels
    ax.set_xlabel('Samples')
    ax.set_ylabel('Genes', labelpad=125)

    # Plot legend
    axcolor = fig.add_axes([0.91, 0.1, 0.02, 0.6])
    plt.colorbar(im, cax=axcolor)

    # display the plot
    plt.show()

In [ ]:
counts_log = np.log(counts + 1)
counts_var = most_variable_rows(counts_log, n=1500)
yr, yc = bicluster(counts_var, linkage_method='ward',
                   distance_metric='euclidean')
with plt.style.context('style/thinner.mplstyle'):
    plot_bicluster(counts_var, yr, yc)

In [ ]:
# Predicting Survival
patients = pd.read_csv('data/patients.csv', index_col=0)
patients.head()

In [ ]:
def survival_distribution_function(lifetimes, right_censored=None):
    """Return the survival distribution function of a set of lifetimes.

    Parameters
    ----------
    lifetimes : array of float or int
        The observed lifetimes of a population. These must be non-negative.
    right_censored : array of bool, same shape as `lifetimes`
        A value of `True` here indicates that this lifetime was not observed.
        Values of `np.nan` in `lifetimes` are also considered to be 
        right-censored.

    Returns
    -------
    sorted_lifetimes : array of float
        The
    sdf : array of float
        Values starting at 1 and progressively decreasing, one level
        for each observation in `lifetimes`.

    Examples
    --------

    In this example, of a population of four, two die at time 1, a
    third dies at time 2, and a final individual dies at an unknown
    time. (Hence, ``np.nan``.)

    >>> lifetimes = np.array([2, 1, 1, np.nan])
    >>> survival_distribution_function(lifetimes)
    (array([ 0.,  1.,  1.,  2.]), array([ 1.  ,  0.75,  0.5 ,  0.25]))
    """
    n_obs = len(lifetimes)
    rc = np.isnan(lifetimes)
    if right_censored is not None:
        rc |= right_censored
    observed = lifetimes[~rc]
    xs = np.concatenate( ([0], np.sort(observed)) )
    ys = np.linspace(1, 0, n_obs + 1)
    ys = ys[:len(xs)]
    return xs, ys

In [ ]:
def plot_cluster_survival_curves(clusters, sample_names, patients,
                                 censor=True):
    """Plot the survival data from a set of sample clusters.

    Parameters
    ----------
    clusters : array of int or categorical pd.Series
        The cluster identity of each sample, encoded as a simple int
        or as a pandas categorical variable.
    sample_names : list of string
        The name corresponding to each sample. Must be the same length
        as `clusters`.
    patients : pandas.DataFrame
        The DataFrame containing survival information for each patient.
        The indices of this DataFrame must correspond to the
        `sample_names`. Samples not represented in this list will be
        ignored.
    censor : bool, optional
        If `True`, use `patients['melanoma-dead']` to right-censor the
        survival data.
    """
    fig, ax = plt.subplots()
    if type(clusters) == np.ndarray:
        cluster_ids = np.unique(clusters)
        cluster_names = ['cluster {}'.format(i) for i in cluster_ids]
    elif type(clusters) == pd.Series:
        cluster_ids = clusters.cat.categories
        cluster_names = list(cluster_ids)
    n_clusters = len(cluster_ids)
    for c in cluster_ids:
        clust_samples = np.flatnonzero(clusters == c)
        # discard patients not present in survival data
        clust_samples = [sample_names[i] for i in clust_samples
                         if sample_names[i] in patients.index]
        patient_cluster = patients.loc[clust_samples]
        survival_times = patient_cluster['melanoma-survival-time'].values
        if censor:
            censored = ~patient_cluster['melanoma-dead'].values.astype(bool)
        else:
            censored = None
        stimes, sfracs = survival_distribution_function(survival_times,
                                                        censored)
        ax.plot(stimes / 365, sfracs)

    ax.set_xlabel('survival time (years)')
    ax.set_ylabel('fraction alive')
    ax.legend(cluster_names)

In [ ]:
from scipy.cluster.hierarchy import fcluster
n_clusters = 3
threshold_distance = (yc[-n_clusters, 2] + yc[-n_clusters+1, 2]) / 2
clusters = fcluster(yc, threshold_distance, 'distance')

plot_cluster_survival_curves(clusters, data_table.columns, patients)