<a href="https://colab.research.google.com/github/venu887/Python-Codes/blob/main/TensorFlow%2BJAX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [91]:
# Tensorflow
import tensorflow as tf
print(tf.__version__)
#Tensor is a multidirectional array that has ability to run on GPU
# Tensor is a generalization of a scalar, Vector and matrix

2.9.2


In [92]:
# Tensor Initialization
x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [93]:
x = tf.constant(4, shape=(1,1),)
print(x)

tf.Tensor([[4]], shape=(1, 1), dtype=int32)


In [94]:
x = tf.constant(4, shape=(1,1),dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [95]:
x= tf.constant([[1,2,3], [4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [96]:
x=tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [97]:
x=tf.zeros((2,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [98]:
x=tf.eye(3)
print(x) #Identical matrix

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [99]:
x=tf.random.normal((3,3,4), mean=1,stddev=3)
print(x)

tf.Tensor(
[[[ 0.08265877  2.7419531  -1.9630508   0.8734042 ]
  [ 0.35297245  2.3282113  -5.265209    3.985714  ]
  [ 0.05258238 -4.6379385   3.265038   -2.6411781 ]]

 [[ 0.9587996   4.199876    2.4333115   0.95690465]
  [ 4.4954877   3.0940685   1.5144134   2.3782954 ]
  [ 0.30045962  2.123345   -0.0421201   3.9992263 ]]

 [[ 1.960843   -2.077887    1.6617393   3.4536366 ]
  [-1.4059992   2.8128028  -1.8457942   1.0225644 ]
  [ 1.3083794  -3.9490013  -1.4663665  -1.3335128 ]]], shape=(3, 3, 4), dtype=float32)


In [100]:
x=tf.random.uniform((1,4), minval=1, maxval=19)
print(x)

tf.Tensor([[14.664306 17.907955 16.300947 12.91554 ]], shape=(1, 4), dtype=float32)


In [101]:
x=tf.range(7)
print(x)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)


In [102]:
x=tf.range(start=1, limit=10, delta=4)
print(x)

tf.Tensor([1 5 9], shape=(3,), dtype=int32)


In [103]:
x= tf.cast(x, dtype=tf.float64) 
#tf.float64 (16,32,64), tf.int(8,16,32,64), tf.bool
print(x)

tf.Tensor([1. 5. 9.], shape=(3,), dtype=float64)


In [104]:
# Mathematical Operations 
x=tf.constant([1,2,3])
y=tf.constant([7,6,5])
z=tf.add(x,y) # or regular z= x+y
print(z)

z=tf.subtract(x,y) # or regular z= x-y
print(z)

z=tf.divide(x,y)# or regular z= x/y
print(z)

z=tf.multiply(x,y) # or regular z= x*y
print(z)

z=tf.tensordot(x,y,axes=1)
print(z)

z=tf.reduce_sum(x*y, axis=0)
print(z)

z=x**5
print (z)

tf.Tensor([8 8 8], shape=(3,), dtype=int32)
tf.Tensor([-6 -4 -2], shape=(3,), dtype=int32)
tf.Tensor([0.14285714 0.33333333 0.6       ], shape=(3,), dtype=float64)
tf.Tensor([ 7 12 15], shape=(3,), dtype=int32)
tf.Tensor(34, shape=(), dtype=int32)
tf.Tensor(34, shape=(), dtype=int32)
tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [105]:
x=tf.random.normal((2,3))
y=tf.random.normal((3,4))
z=tf,tf.matmul(x,y)
#or
z=x @ y
print(z)

tf.Tensor(
[[-2.2904959  -0.48160866 -1.7096498   2.360908  ]
 [ 0.33316863  0.11178967  0.19841883  0.94437623]], shape=(2, 4), dtype=float32)


In [106]:
# Indexing on Tensor
x=tf.constant([0,1,2,3,2,3,1,2,3])
print(x[:])
print(x[1:]) # start from second position
print(x[1:3]) # selecting only first two numbers
print(x[::2]) # Removed even position number
print(x[::-1]) # making it in to Riverse order

tf.Tensor([0 1 2 3 2 3 1 2 3], shape=(9,), dtype=int32)
tf.Tensor([1 2 3 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([0 2 2 1 3], shape=(5,), dtype=int32)
tf.Tensor([3 2 1 3 2 3 2 1 0], shape=(9,), dtype=int32)


In [107]:
x=tf.constant([0,1,2,3,2,3,1,2,3])
indices=tf.constant([0, 3])
print(indices)
x_ind=tf.gather(x, indices)
print(x_ind)

x=tf.constant([[1,2],
               [3,4],
               [5,6]])
print(x[0,:])
print(x[0:2,:])

tf.Tensor([0 3], shape=(2,), dtype=int32)
tf.Tensor([0 3], shape=(2,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [108]:
# Reshaping 
x= tf.range(9)
print(x)
x=tf.reshape(x, (3,3))
print(x)
x=tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)


In [109]:
# Create Neural Network
# short introduction uses Keras to:
# Load a prebuilt dataset.
# Build a neural network machine learning model that classifies images.
# Train this neural network.
# Evaluate the accuracy of the model.
import tensorflow as tf
print("TensorFlow version:", tf.__version__)
# we need to use Keras from tensorflow for official functional API

# Load a dataset
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

TensorFlow version: 2.9.2


In [110]:
# Build a machine learning model
# Build a tf.keras.Sequential model by stacking layers.
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [111]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.3240631 ,  0.23687169, -0.03808363,  0.0149194 , -0.15563092,
        -0.00746007,  0.3362402 , -0.6026445 , -0.45815885, -0.40826464]],
      dtype=float32)

In [112]:
# The tf.nn.softmax function converts these logits to probabilities for each class:
tf.nn.softmax(predictions).numpy()

array([[0.14225069, 0.13037299, 0.09903212, 0.10442272, 0.08804931,
        0.10211174, 0.14399348, 0.05631063, 0.06506384, 0.06839251]],
      dtype=float32)

In [113]:
# Define a loss function for training using losses.SparseCategoricalCrossentropy, which takes a vector of logits and a True index and returns a scalar loss for each example.
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

2.2816875

In [114]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [115]:
# Train and evaluate your model
# Use the Model.fit method to adjust your model parameters and minimize the loss
model.fit(x_train, y_train, epochs=5)
# The Model.evaluate method checks the models performance, usually on a "Validation-set" or "Test-set".
model.evaluate(x_test,  y_test, verbose=2)

#The image classifier is now trained to ~98% accuracy on this dataset. To learn more, read the TensorFlow tutorials.
# If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

Epoch 1/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.3022 - accuracy: 0.9121
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1460 - accuracy: 0.9568
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1094 - accuracy: 0.9667
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0898 - accuracy: 0.9722
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0747 - accuracy: 0.9764
313/313 - 1s - loss: 0.0721 - accuracy: 0.9774 - 802ms/epoch - 3ms/step


In [116]:
# trained a machine learning model using a prebuilt dataset using the Keras API
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[9.4559795e-08, 2.2212273e-08, 5.7652128e-06, 1.4501590e-04,
        2.7022615e-09, 3.5196191e-08, 9.7643431e-14, 9.9984431e-01,
        2.4379048e-07, 4.5448373e-06],
       [2.3391724e-08, 4.2654973e-04, 9.9953783e-01, 3.2717540e-05,
        3.1138138e-15, 5.0856283e-07, 9.5479614e-08, 2.8558041e-12,
        2.2471675e-06, 1.9083221e-11],
       [4.5042274e-08, 9.9893087e-01, 3.4687977e-04, 1.3090905e-05,
        3.3022170e-05, 1.9417621e-05, 3.4477544e-05, 4.8568877e-04,
        1.3491965e-04, 1.4991223e-06],
       [9.9995899e-01, 3.9100562e-10, 3.1076509e-06, 3.7936513e-08,
        1.7449878e-09, 5.0114585e-07, 6.7019146e-06, 2.0134439e-05,
        7.0252865e-10, 1.0615852e-05],
       [4.2537620e-05, 9.8327915e-09, 1.4300374e-05, 2.8493469e-07,
        9.9343830e-01, 1.1247723e-05, 1.3119777e-04, 7.4192729e-05,
        2.4415118e-05, 6.2634870e-03]], dtype=float32)>

In [117]:
# this is the second way of importing keras and layers or datasets like mnist for NN
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

In [118]:
(x_train,y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)
