<a href="https://colab.research.google.com/github/venu887/Python-Codes/blob/main/TensorFlow%2BJAX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Tensorflow
import tensorflow as tf
print(tf.__version__)
#Tensor is a multidirectional array that has ability to run on GPU
# Tensor is a generalization of a scalar, Vector and matrix

2.9.2


In [3]:
# Tensor Initialization
x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
x = tf.constant(4, shape=(1,1),)
print(x)

tf.Tensor([[4]], shape=(1, 1), dtype=int32)


In [6]:
x = tf.constant(4, shape=(1,1),dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [8]:
x= tf.constant([[1,2,3], [4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [10]:
x=tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [12]:
x=tf.zeros((2,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [16]:
x=tf.eye(3)
print(x) #Identical matrix

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [18]:
x=tf.random.normal((3,3,4), mean=1,stddev=3)
print(x)

tf.Tensor(
[[[ 0.47576487  6.7096605   5.6920114  -1.0356097 ]
  [-3.5636115  -1.7130196   0.10244471  3.712285  ]
  [ 1.171627    0.9363997   2.4245982   0.6717675 ]]

 [[-2.6332579  -2.7365065   0.04957855  0.07504684]
  [ 0.73908484  0.51716137  0.21260875  2.1005945 ]
  [ 4.581653    0.8904792  -0.54005384  3.2392058 ]]

 [[ 2.2960625  -0.5275712   2.0410755   5.8958964 ]
  [-1.4920256   2.3478744   3.9073331  -0.5024595 ]
  [-0.8980355  -3.5556111  -7.9330835  -4.2066765 ]]], shape=(3, 3, 4), dtype=float32)


In [19]:
x=tf.random.uniform((1,4), minval=1, maxval=19)
print(x)

tf.Tensor([[15.173649  18.87234    1.6425521  8.640641 ]], shape=(1, 4), dtype=float32)


In [21]:
x=tf.range(7)
print(x)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)


In [24]:
x=tf.range(start=1, limit=10, delta=4)
print(x)

tf.Tensor([1 5 9], shape=(3,), dtype=int32)


In [26]:
x= tf.cast(x, dtype=tf.float64) 
#tf.float64 (16,32,64), tf.int(8,16,32,64), tf.bool
print(x)

tf.Tensor([1. 5. 9.], shape=(3,), dtype=float64)


In [30]:
# Mathematical Operations 
x=tf.constant([1,2,3])
y=tf.constant([7,6,5])
z=tf.add(x,y) # or regular z= x+y
print(z)

z=tf.subtract(x,y) # or regular z= x-y
print(z)

z=tf.divide(x,y)# or regular z= x/y
print(z)

z=tf.multiply(x,y) # or regular z= x*y
print(z)

z=tf.tensordot(x,y,axes=1)
print(z)

tf.Tensor([8 8 8], shape=(3,), dtype=int32)
tf.Tensor([-6 -4 -2], shape=(3,), dtype=int32)
tf.Tensor([0.14285714 0.33333333 0.6       ], shape=(3,), dtype=float64)
tf.Tensor([ 7 12 15], shape=(3,), dtype=int32)
tf.Tensor(34, shape=(), dtype=int32)
